ninetycats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests
  post 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve', as: 'cat_rental_request_approve'
  post 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny', as: 'cat_rental_request_deny'
end

ninetycats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninetycats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
COLORS = %w(brown black white orange red blue green yellow purple)

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS, message: "Not a valid color" }
  validates :sex, inclusion: { in: %w(M F I), message: "Not a valid sex" }

  has_many :cat_rental_requests,
    dependent: :destroy,
    primary_key: :id,
    foreign_key:  :cat_id,
    class_name: 'CatRentalRequest'


  def age
    Time.now.year - birth_date.year
  end

  def self.colors
    COLORS
  end

end

ninetycats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED), message: "Not a valid status" }
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'Cat'


    def approve!
      # CatRentalRequest.transaction do
        self.status = 'APPROVED'
        self.save!
        overlapping_pending_requests.each do |request|
          request.deny!
        end
      # end
    end

    def deny!
      self.status = "DENIED"
      self.save!
    end

  # private

  def overlapping_requests
    check_overlap = CatRentalRequest.where("start_date BETWEEN ? AND ? OR end_date BETWEEN ? AND ?", self.start_date, self.end_date , self.start_date, self.end_date)
    # full_check = check_overlap.where("start_date < ? AND end_date > ?", self.start_date, self.end_date)
    with_cat = check_overlap.where("cat_id = ?", self.cat_id)
    with_cat
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end


  def does_not_overlap_approved_request
    return if self.status == "DENIED"
    if overlapping_approved_requests.exists?
      errors[:overlapping] << "There is an overlapping request"
    end
  end

end

ninetycats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

ninetycats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
  end

  def create
    @new_cat_rental = CatRentalRequest.new(rental_request_params)

    if @new_cat_rental.save
      redirect_to cat_url(@new_cat_rental.cat_id)
    else
      redirect_to new_cat_rental_request_url
    end
  end

  def approve
    @cat_rental = find_rental
    @cat_rental.approve!
    redirect_to cats_url
  end

  def deny
    @cat_rental = find_rental
    @cat_rental.deny!
    redirect_to cats_url
  end

  private

  def rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

  def find_rental
    CatRentalRequest.find(params[:id])
  end
end

ninetycats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def new
    @COLORS = Cat.colors
    @cat = Cat.new
  end

  def show
    @cat = find_cat
    @cat_rentals = @cat.cat_rental_requests.order(:start_date)
  end

  def create
    @new_cat = Cat.new(cat_params)

    if @new_cat.save
      redirect_to cats_url(@new_cat)
    else
      render :new
    end
  end

  def edit
    @cat = find_cat
    @COLORS = Cat.colors
  end

  def update
    @cat = find_cat
    if @cat.update_attributes(cat_params)
      redirect_to cats_url(@cat)
    else
      redirect_to :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

  def find_cat
    Cat.find(params[:id])
  end
end

ninetycats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninetycats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

ninetycats/app/helpers/cats_helper.rb
module CatsHelper
end

ninetycats/app/views/cat_rental_requests/new.html.erb
<h1> Rent a new cat! </h1>

<form  action= "<%=cat_rental_requests_url%>" method="post">

  <label for="cat_id">Cat ID</label>
  <select name="cat_rental_request[cat_id]">
    <option value="" disabled selected>Please select cat id</option>
    <% @cats.each do |cat| %>
      <option value= "<%=cat.id%>" ><%= cat.id %></option>
    <% end %>
  </select>

  <br></br>

  <label for="start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" value>

  <br> </br>

  <label for="end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]" value>

  <br> </br>

  <input type="submit" value="Submit your request!">

</form>

ninetycats/app/views/cats/_all_cats.html.erb
<%= cat.name %>
<%= link_to "#{cat.name}'s profile", cat_url(cat)%>
<br>
<br/>

ninetycats/app/views/cats/_form.html.erb
<% action == :edit ? action_url = cat_url(cat) : action_url = cats_url%>

<form  action= "<%=action_url%>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input type="text" name="cat[name]" value= "<%= cat.name %>" >

  <br></br>

  <label for="birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" value= "<%= cat.birth_date%>" >

  <br> </br>

  <label for="color">Color</label>
  <select name="cat[color]">
    <option value="" disabled <%= action == :edit ? "" : 'selected' %> >Please select color</option>
    <% @COLORS.each do |color| %>
      <option value= "<%=color%>" <%= cat.color == color ? 'selected' : "" %> ><%= color %></option>
    <% end %>
  </select>

  <br> </br>

  <label for="cat_sex_male">Male</label>
  <input type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? 'checked' : "" %>>
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? 'checked' : "" %>>
  <label for="cat_sex_intersex">Intersex</label>
  <input type="radio" name="cat[sex]" value="I" <%= cat.sex == 'I' ? 'checked' : "" %> >

  <br> </br>

  <label for="description">Description</label>
  <textarea name="cat[description]" rows="8" cols="80"> <%= @cat.description %>  </textarea>

  <br> </br>

  <input type="submit" value= "<%= action == :edit ? "Update your cat" : "Submit your cat!" %>" >

</form>

ninetycats/app/views/cats/edit.html.erb
<h1> Update <%= @cat.name %> </h1>
<h4> Enter in the new information</h4>

<%= render "form", action: :edit, method: :PATCH, cat: @cat %>
<!--
<form  action= "<%=cat_url(@cat)%>" method="post">
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name</label>
  <input type="text" name="cat[name]" value= "<%= @cat.name %>">

  <br></br>

  <label for="birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" value = "<%= @cat.birth_date %>">

  <br> </br>

  <label for="color">Color</label>
  <select name="cat[color]">
    <option value="" disabled>Please select color</option>
    <% @COLORS.each do |color| %>
      <option value= "<%=color%>" "<% @cat.color == color ? 'selected' : "" %>" ><%= color %></option>
    <% end %>
  </select>

  <br> </br>

  <label for="cat_sex_male">Male</label>
  <input type="radio" name="cat[sex]" value="M" checked = "<% @cat.sex == 'M' ? 'checked' : "" %>">
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" value="F" checked = "<% @cat.sex == 'F' ? 'checked' : "" %>">
  <label for="cat_sex_intersex">Intersex</label>
  <input type="radio" name="cat[sex]" value="I" checked = "<% @cat.sex == 'I' ? 'checked' : "" %>">

  <br> </br>

  <label for="description">Description</label>
  <textarea name="cat[description]" rows="8" cols="80"> <%= @cat.description %> </textarea>

  <br> </br>

  <input type="submit" value="Submit your cat!">

</form> -->

ninetycats/app/views/cats/index.html.erb
<h1> Ninety cats: a purrfect evening</h1>

<% @cats.each do |cat| %>
  <%= render 'all_cats', cat: cat %>
<% end %>

<br></br>

<%= link_to "Add a cat", new_cat_url %>

ninetycats/app/views/cats/new.html.erb
<h1> New Cat! </h1>
<h4> We're so excited to have your cat join us!</h4>

<%= render "form", action: :new, method: :POST, cat: @cat %>

<!--
<form  action= "<%=cats_url%>" method="post">

  <label for="name">Name</label>
  <input type="text" name="cat[name]" value>

  <br></br>

  <label for="birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" value>

  <br> </br>

  <label for="color">Color</label>
  <select name="cat[color]">
    <option value="" disabled selected>Please select color</option>
    <% @COLORS.each do |color| %>
      <option value= "<%=color%>" ><%= color %></option>
    <% end %>
  </select>

  <br> </br>

  <label for="cat_sex_male">Male</label>
  <input type="radio" name="cat[sex]" value="M">
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" value="F">
  <label for="cat_sex_intersex">Intersex</label>
  <input type="radio" name="cat[sex]" value="I">

  <br> </br>

  <label for="description">Description</label>
  <textarea name="cat[description]" rows="8" cols="80"></textarea>

  <br> </br>

  <input type="submit" value="Submit your cat!">

</form> -->

ninetycats/app/views/cats/show.html.erb
<h1><%=@cat.name%></h1>

<p>Get to know <%=@cat.name%></p>
<table>
  <thead>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
  </thead>

  <tbody>

    <tr>
      <td>Age (yrs):</td>
      <td> <%= @cat.age%> </td>
    </tr>
    <% @cat.attributes.each do |k, v| %>
    <% next if %w(id created_at updated_at).include?(k) %>
    <tr>
      <td><%= k %>:</td>
      <td><%= v %></td>
    </tr>
    <% end %>
  </tbody>

</table>

<%= link_to "Edit this cat", edit_cat_url %>


<h2>Rental Requests</h2>
<table>
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th>Approve</th>
      <th>Deny</th>
    </tr>
  </thead>

  <tbody>

    <% @cat_rentals.each do |rental| %>
      <% next if rental.status == "DENIED" %>
      <tr>
        <td><%= rental.start_date %></td>
        <td><%= rental.end_date %></td>
        <td> <%= rental.status %> </td>
      <% if rental.status == "PENDING" %>
        <td> <%= button_to 'APPROVE', cat_rental_request_approve_url(rental.cat_id)  %> </td>
        <td> <%= button_to 'DENY', cat_rental_request_deny_url(rental.cat_id)  %> </td>
        <%end%>
      </tr>

      <% end %>
  </tbody>

</table>

<%= link_to 'Request rental', new_cat_rental_request_url %>

<br></br>

<%= link_to "Main page", cats_url %>

ninetycats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninetycats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>